"""Released FluidSim 0.9.0 solver-specific metadata, reviewed 2026-10-01.

Only bundled Cartesian profiles; extensions must be reviewed separately.
Source: Simul.create_default_params() and Simul.InfoSolver().classes.State.
"""

PROFILES = {'ns2d': {'initializations': ['from_file',
                              'from_simul',
                              'in_script',
                              'constant',
                              'noise',
                              'jet',
                              'dipole'],
          'forcing': ['in_script',
                      'in_script_coarse',
                      'pseudo_spectral',
                      'proportional',
                      'tcrandom',
                      'tcrandom_anisotropic'],
          'physics': ['beta'],
          'outputs': ['phys_fields',
                      'spectra',
                      'spectra_multidim',
                      'spatial_means',
                      'spect_energy_budg',
                      'increments',
                      'temporal_spectra',
                      'spatiotemporal_spectra'],
          'required_state': ['rot'],
          'state_fields': ['ux', 'uy', 'rot']},
 'ns2d.bouss': {'initializations': ['from_file',
                                    'from_simul',
                                    'in_script',
                                    'constant',
                                    'noise',
                                    'jet',
                                    'dipole'],
                'forcing': ['in_script',
                            'in_script_coarse',
                            'pseudo_spectral',
                            'proportional',
                            'tcrandom',
                            'tcrandom_anisotropic'],
                'physics': ['beta'],
                'outputs': ['phys_fields',
                            'spectra',
                            'spectra_multidim',
                            'spatial_means',
                            'spect_energy_budg',
                            'increments',
                            'temporal_spectra',
                            'spatiotemporal_spectra'],
                'required_state': ['rot', 'b'],
                'state_fields': ['ux', 'uy', 'rot', 'b']},
 'ns2d.strat': {'initializations': ['from_file',
                                    'from_simul',
                                    'in_script',
                                    'constant',
                                    'noise',
                                    'jet',
                                    'dipole',
                                    'linear_mode'],
                'forcing': ['in_script',
                            'in_script_coarse',
                            'pseudo_spectral',
                            'proportional',
                            'tcrandom',
                            'tcrandom_anisotropic'],
                'physics': ['N', 'beta'],
                'outputs': ['phys_fields',
                            'spectra',
                            'spectra_multidim',
                            'spatial_means',
                            'spect_energy_budg',
                            'increments',
                            'temporal_spectra',
                            'spatiotemporal_spectra'],
                'required_state': ['rot', 'b'],
                'state_fields': ['ux', 'uy', 'rot', 'b']},
 'ns3d': {'initializations': ['from_file',
                              'from_simul',
                              'in_script',
                              'constant',
                              'noise',
                              'dipole'],
          'forcing': ['in_script',
                      'in_script_coarse',
                      'pseudo_spectral',
                      'proportional',
                      'taylor_green',
                      'tcrandom',
                      'tcrandom_anisotropic',
                      'watu_coriolis'],
          'physics': ['f'],
          'outputs': ['phys_fields',
                      'spectra',
                      'spatial_means',
                      'spect_energy_budg',
                      'temporal_spectra',
                      'spatiotemporal_spectra',
                      'cross_corr'],
          'required_state': ['vx', 'vy', 'vz'],
          'state_fields': ['vx', 'vy', 'vz']},
 'ns3d.bouss': {'initializations': ['from_file',
                                    'from_simul',
                                    'in_script',
                                    'constant',
                                    'noise',
                                    'dipole'],
                'forcing': ['in_script',
                            'in_script_coarse',
                            'pseudo_spectral',
                            'proportional',
                            'taylor_green',
                            'tcrandom',
                            'tcrandom_anisotropic',
                            'watu_coriolis'],
                'physics': ['N', 'f'],
                'outputs': ['phys_fields',
                            'spectra',
                            'spatial_means',
                            'spect_energy_budg',
                            'temporal_spectra',
                            'spatiotemporal_spectra',
                            'cross_corr'],
                'required_state': ['vx', 'vy', 'vz', 'b'],
                'state_fields': ['vx', 'vy', 'vz', 'b']},
 'ns3d.strat': {'initializations': ['from_file',
                                    'from_simul',
                                    'in_script',
                                    'constant',
                                    'noise',
                                    'dipole'],
                'forcing': ['in_script',
                            'in_script_coarse',
                            'pseudo_spectral',
                            'proportional',
                            'taylor_green',
                            'tcrandom',
                            'tcrandom_anisotropic',
                            'watu_coriolis'],
                'physics': ['N', 'f'],
                'outputs': ['phys_fields',
                            'spectra',
                            'spatial_means',
                            'spect_energy_budg',
                            'temporal_spectra',
                            'spatiotemporal_spectra',
                            'cross_corr'],
                'required_state': ['vx', 'vy', 'vz', 'b'],
                'state_fields': ['vx', 'vy', 'vz', 'b']},
 'plate2d': {'initializations': ['from_file',
                                 'from_simul',
                                 'in_script',
                                 'constant',
                                 'noise',
                                 'harmonic'],
             'forcing': ['in_script', 'in_script_coarse', 'proportional', 'tcrandom'],
             'physics': ['beta'],
             'outputs': ['phys_fields', 'spectra', 'spatial_means', 'correl_freq'],
             'required_state': ['w', 'z'],
             'state_fields': ['w', 'z']},
 'sw1l': {'initializations': ['from_file',
                              'from_simul',
                              'in_script',
                              'constant',
                              'noise',
                              'jet',
                              'dipole',
                              'wave',
                              'vortex_grid'],
          'forcing': ['in_script',
                      'in_script_coarse',
                      'potential',
                      'proportional',
                      'random',
                      'tcrandom',
                      'waves',
                      'waves_vortices'],
          'physics': ['beta', 'c2', 'f'],
          'outputs': ['phys_fields',
                      'spectra',
                      'spatial_means',
                      'spect_energy_budg',
                      'increments',
                      'pdf',
                      'time_signals_fft'],
          'required_state': ['ux', 'uy', 'eta'],
          'state_fields': ['ux', 'uy', 'eta', 'rot']},
 'sw1l.exactlin': {'initializations': ['from_file',
                                       'from_simul',
                                       'in_script',
                                       'constant',
                                       'noise',
                                       'jet',
                                       'dipole',
                                       'wave',
                                       'vortex_grid'],
                   'forcing': ['in_script',
                               'in_script_coarse',
                               'potential',
                               'proportional',
                               'random',
                               'tcrandom',
                               'waves',
                               'waves_vortices'],
                   'physics': ['beta', 'c2', 'f'],
                   'outputs': ['phys_fields',
                               'spectra',
                               'spatial_means',
                               'spect_energy_budg',
                               'increments',
                               'pdf',
                               'time_signals_fft'],
                   'required_state': ['ux', 'uy', 'eta'],
                   'state_fields': ['ux', 'uy', 'eta', 'rot']},
 'sw1l.modified': {'initializations': ['from_file',
                                       'from_simul',
                                       'in_script',
                                       'constant',
                                       'noise',
                                       'jet',
                                       'dipole',
                                       'wave',
                                       'vortex_grid'],
                   'forcing': ['in_script',
                               'in_script_coarse',
                               'potential',
                               'proportional',
                               'random',
                               'tcrandom',
                               'waves',
                               'waves_vortices'],
                   'physics': ['beta', 'c2', 'f'],
                   'outputs': ['phys_fields',
                               'spectra',
                               'spatial_means',
                               'spect_energy_budg',
                               'increments',
                               'pdf',
                               'time_signals_fft'],
                   'required_state': ['ux', 'uy', 'eta'],
                   'state_fields': ['ux', 'uy', 'eta']},
 'sw1l.onlywaves': {'initializations': ['from_file',
                                        'from_simul',
                                        'in_script',
                                        'constant',
                                        'noise',
                                        'jet',
                                        'dipole',
                                        'wave',
                                        'vortex_grid'],
                    'forcing': ['in_script',
                                'in_script_coarse',
                                'potential',
                                'proportional',
                                'random',
                                'tcrandom',
                                'waves',
                                'waves_vortices'],
                    'physics': ['beta', 'c2', 'f'],
                    'outputs': ['phys_fields',
                                'spectra',
                                'spatial_means',
                                'spect_energy_budg',
                                'increments',
                                'pdf',
                                'time_signals_fft'],
                    'required_state': ['ux', 'uy', 'eta'],
                    'state_fields': ['ux', 'uy', 'eta']},
 'waves2d': {'initializations': ['from_file', 'from_simul', 'in_script', 'constant', 'noise'],
             'forcing': ['in_script', 'in_script_coarse', 'proportional', 'tcrandom'],
             'physics': ['c2', 'f'],
             'outputs': ['phys_fields'],
             'required_state': ['f', 'g'],
             'state_fields': ['f', 'g']}}
